# Generated by Django 6.0 on 2026-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
