# Generated by Django 6.0 on 2026-02-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalysis',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
