# Generated by Django 6.0 on 2026-08-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_useranalysis_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnalysis',
        ),
    ]
