import React from "react";
import {Page, PageContent, Paragraph, Grid, Card} from "grommet";
import { Grommet, Box, Accordion, AccordionPanel, Text, Heading } from "grommet";

const theme = {
  global: {
    font: {
      family: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    colors: {
      brand: "#D9A7C7", 
      "accent-1": "#FCE4EC",
      "accent-2": "#F8BBD0",
      background: "#85566d",
      text: "#3D2B3D",
    }, 
  },
};

const PrivacyPolicy= () => {
  return (

       <Box
                fill
                align="center"
                justify="center"
                pad="large"
                round="small"
                background="linear-gradient(135deg, #f7d4e8 0%, #d8b4fe 100%)"
                style={{ minHeight: "calc(100vh - 80px)" }}
            
              >
  <Page kind="narrow">
      <PageContent background="light-3">

          <Heading
            level={2}
            margin={{ bottom: "small" }}
            color="text"
            style={{ fontWeight: 600 }}
          >
            HijabMatch Privacy Policy
          </Heading>
          <Text size="small" color="dark-4" margin={{ bottom: "medium" }}>
            Last updated: May 2026
          </Text>

          <Accordion animate multiple>
            <AccordionPanel label="1. What information does HijabMatch collect?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  We only collect the essentials needed to give you accurate undertone and hijab‑shade
                  recommendations. This includes:
                </Text>
                <Box pad={{ vertical: "xsmall", left: "small" }}>
                  <Text size="small">• The photo you upload</Text>
                  <Text size="small">• The undertone analysis generated by our AI</Text>
                  <Text size="small">• Basic device information (browser type, IP address, etc.)</Text>
                </Box>
                <Text size="small" color="text">
                  We do not collect analytics, marketing data, or anything unnecessary.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="2. How is my photo used?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  Your photo is used only for:
                </Text>
                <Box pad={{ vertical: "xsmall", left: "small" }}>
                  <Text size="small">• Detecting your undertone</Text>
                  <Text size="small">• Matching you with flattering hijab shades</Text>
                </Box>
                <Text size="small" color="text">
                  We never use your image for advertising, training external AI models, or sharing with
                  third parties.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="3. Do I need an account to use HijabMatch?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  No — HijabMatch is completely guest‑based. You can enjoy the full experience without
                  creating an account, logging in, or sharing personal details.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="4. How long is my photo stored?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  Your photo is stored securely in our database only for as long as needed to
                  perform the analysis and keep the system functioning smoothly.
                </Text>
                <Text size="small" color="text" margin={{ top: "xsmall" }}>
                  We are finalizing a fixed retention period, and this policy will be updated once it’s
                  set. If you ever want your photo deleted sooner, you can request it anytime.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="5. How does HijabMatch protect my data?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  We take your privacy seriously. Your data is protected using:
                </Text>
                <Box pad={{ vertical: "xsmall", left: "small" }}>
                  <Text size="small">• Secure server storage</Text>
                  <Text size="small">• Encrypted connections (HTTPS)</Text>
                  <Text size="small">• Restricted internal access</Text>
                  <Text size="small">• Regular system monitoring</Text>
                </Box>
                <Text size="small" color="text">
                  We treat your photo with the same care we’d want for our own.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="6. Do you share my information with anyone?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  No. We do not share, sell, or trade your information with advertisers, marketers, or
                  social platforms.
                </Text>
                <Text size="small" color="text" margin={{ top: "xsmall" }}>
                  If we use trusted hosting or storage providers, they are required to protect your data
                  and cannot use it for their own purposes.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="7. Do you use cookies or tracking tools?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  We currently use only essential cookies that help the app function properly. We do not
                  use Google Analytics or any tracking/advertising cookies at this time.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="8. Is HijabMatch safe for children?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  HijabMatch is designed for users 13 and older. We do not knowingly collect information
                  from children.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="9. What rights do I have over my data?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  You may request:
                </Text>
                <Box pad={{ vertical: "xsmall", left: "small" }}>
                  <Text size="small">• Deletion of your photo</Text>
                  <Text size="small">• Access to the data we have stored</Text>
                  <Text size="small">• Correction of any information you provided</Text>
                </Box>
                <Text size="small" color="text" margin={{ top: "xsmall" }}>
                  To make a request, email us at{" "}
                  <strong>support@hijabmatch.com</strong> {/* change to your real email */}
                  .
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="10. Will this Privacy Policy change?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  As HijabMatch grows, we may update this policy. When we do, we’ll update the “Last
                  updated” date so you always know what’s new.
                </Text>
              </Box>
            </AccordionPanel>

            <AccordionPanel label="11. How can I contact you?">
              <Box pad={{ vertical: "small" }}>
                <Text size="small" color="text">
                  If you have questions or concerns, we’re here for you. You can reach us at:
                </Text>
                <Text size="small" margin={{ top: "xsmall" }}>
                  📧 <strong>support@hijabmatch.com</strong> {/* change to your real email */}
                </Text>
              </Box>
            </AccordionPanel>
          </Accordion>
        </PageContent>
        </Page>
      </Box>
   
  );
};

export default PrivacyPolicy;
